### ISSUE TITLE
[BUG] Missing network-status annotation

### ISSUE THREAD

**Issue by LionelJouin** [k8snetworkplumbingwg/multus-dynamic-networks-controller#157]
**Describe the bug**

The k8s.v1.cni.cncf.io/network-status is missing when adding and removing network attachment elements at the same time. 

The reconcile loop will add the new network attachment first, then will update the k8s.v1.cni.cncf.io/network-status annotation based on the pod got at the beginning of the reconcile loop. After that, the reconcile will go to delete the non longer existing network attachment and will update the k8s.v1.cni.cncf.io/network-status annotation based on the pod got at the beginning of the reconcile loop (so without the newly added network status).

**Expected behavior**

To solve the problem, I see 2 solutions:
1. After each pod network status annotation update, the controller should get the pod again (which will contain the newly added network status).
2. Multus should handle the annotation by itself instead of leaving the responsibility to the caller.

**To Reproduce**
1. Have a running pod with a network attachment (so annotation k8s.v1.cni.cncf.io/network + k8s.v1.cni.cncf.io/network-status), let's say interface A.
2. Delete the element for interface A in k8s.v1.cni.cncf.io/network and add a new different one, let's say interface B.
3. Check the network status annotation. There will be no status for interface B.

**Environment**:
- multus-dynamic-networks-controller version: latest-amd64
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- OS (e.g. from /etc/os-release): N/A
- Controller configuration (`criSocketPath` / `multusSocketPath`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
/

**Comment by maiqueb** [comment]
hey o/

The more I look at this issue the more I think I never intended for people to actually mix adds / dels in the same operation.

Of course ... once the toothpaste is out of the tube, there's no putting it back in.

I agree this is problematic; IMO we should either:
- document this is a no-go. At the end of the day, users have the current work-around of performing 2 updates ... This provides bad user experience unfortunately. 
- fix it. I'll analyze your proposed fixes below:

> After each pod network status annotation update, the controller should get the pod again (which will contain the newly added network status).

I would prefer something like this, but, AFAIU, this breaks the Kubernetes controller pattern - you **read** via informers, and write to the API. 

Let me pick your brain for a sec: what about we process the **added** interfaces, then return if we actually added them ? I think the network status update (triggered by the delegate plugin) will just trigger another update event, which we'll catch, and we'll spot the desired / current state is again different, and process the deletes in a "follow-up" iteration. 

Am I making sense ? @LionelJouin 

Thanks for opening the issue :)

**Comment by LionelJouin** [comment]
Thank you for your answer,

> I would prefer something like this, but, AFAIU, this breaks the Kubernetes controller pattern - you read via informers, and write to the API.

Instead of updating `addNetworks` and `removeNetworks` functions (https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/v0.2.1/pkg/controller/pod.go), we could just return the attachmentResults from these functions and update the status after adding/deleting the attachment (errors will have to be handled somehow).

> Let me pick your brain for a sec: what about we process the added interfaces, then return if we actually added them ? I think the network status update (triggered by the delegate plugin) will just trigger another update event, which we'll catch, and we'll spot the desired / current state is again different, and process the deletes in a "follow-up" iteration.

This would mean, we would need to detect if an interface has been added, then quit the current reconcile iteration, and wait for the new one to be enqueued. I believe this would complexify the system.

**Comment by LionelJouin** [comment]
Thank you,
I am currently working on this issue, and will try to provide a fix soon.

**Comment by maiqueb** [comment]
Happy to assist you in any way. 

Thank you for improving the project.
