### ISSUE TITLE
[BUG] Can't hotunplug podInterface which is not hotplug and primaryPodInterface(eth0)

### ISSUE THREAD

**Issue by Longchuanzheng** [k8snetworkplumbingwg/multus-dynamic-networks-controller#209]
**Describe the bug**
Unable to hot unplug the pod interface that is not hot-plugged and the primary pod interface (eth0) because the add request body contains the pod container ID, while the kubelet uses the sandbox ID.

**Expected behavior**
Honestly, I think unable to hotunplug podInterface which is not hotplug is acceptable. While I am curious as to why multus-dynamic-networks-controller send add command different form kubelet (using containerid instead of sandbox id?)

**To Reproduce**
1. create a pod with two interface
2. hotunplug the secand interface

**Environment**:
- multus-dynamic-networks-controller version: N/A
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- OS (e.g. from /etc/os-release): N/A
- Controller configuration (`criSocketPath` / `multusSocketPath`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.

**Comment by maiqueb** [comment]
It is not in scope to detach the pod's cluster network.

IMO, at most, this is a documentation bug where we make that non-goal more explicit.

@LionelJouin thoughts ?

**Comment by maiqueb** [comment]
Regarding un-plugging an original secondary interface, if that indeed happens it is a bug for sure. 

We'll get to it eventually. 

Retrieving the sandbox ID shouldn't be too hard (I assume it is listed by the CRI in the pod containers ...).

**Comment by LionelJouin** [comment]
I agree, I think the default pod network is out of the scope. For multus-dynamic-networks-controller to be able to delete a network, it should be in the `k8s.v1.cni.cncf.io/networks` annotation, and I don't think the default one could be there (it is only in the `k8s.v1.cni.cncf.io/network-status` annotation).

I tried to reproduce this issue based on the description, I haven't noticed any problem, my network has been deleted as expected. Maybe the DEL has failed?

Could it be possible to get the logs of the multus-dynamic-networks-controller pod running on the same node as the pod in which you try to delete the network? And events of the pod too.

Also, could it be possible to know the versions used (Multus (Thick version must be used)).

**Comment by maiqueb** [comment]
IIUC, this request is asserted in https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/489cb557d9a7b706a42a3fd233fb1977767bf2be/e2e/e2e_test.go#L128 which is passing (... in containerd runtimes).

We'll need to check it in cri-o manually.

**Comment by Longchuanzheng** [comment]
> Also, which runtime are you using ?... crio / containerd ? @Longchuanzheng

I am using containerd.

**Comment by Longchuanzheng** [comment]
These problem can reproduce with specific cni plugin (I use kube-ovn).
IMO, most of the cni plugin dosen't use "CNI_CONTAINERID" arg in add/del request to do real add/del process. In these plugins we have no problem.
While in kube-ovn interface name is generate by "CNI_CONTAINERID" arg in add/del request. I find multus-dynamic-networks-controller generate "CNI_CONTAINERID" just use containerid in pod which is different form kubelet. In this way, if the interface is create by kubelet add request, kubeovn unable to handle del request send by multus-dynamic-networks-controller, because "CNI_CONTAINERID" is different in kubelet and multus-dynamic-networks-controller for same pod.

**Comment by Longchuanzheng** [comment]
For example,
![image](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/assets/49519342/495b119e-f956-4af4-935f-b3affc1c4c32)
above picture is about kube-ovn log for add eth0 and net1 when create pod and hotunplug net1. ConfigureNic is add Nic process, deleteNic is delete Nic process. ContainerID is different in add and hotunplug request for the same pod.

**Comment by maiqueb** [comment]
> Thank you for the explanation, I understand now.
> 
> Pod Sandbox ID can be retrieved by listing the containers and filtering by container ID (https://github.com/kubernetes/cri-api/blob/v0.29.2/pkg/apis/runtime/v1/api.proto#L78)
> 
> The response will contain the pod sandbox ID: https://github.com/kubernetes/cri-api/blob/v0.29.2/pkg/apis/runtime/v1/api.proto#L1191
> 
> The current way to get the container ID is by retrieving the first container status of the pod: https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/v0.3.3/pkg/controller/pod.go#L479 A new function like NetNS(containerID) for the container runtime could be implemented.

Keep in mind retrieving the sandbox ID seems to be runtime specific. 

For containerd we have automation and e2e, thus we're covered, but for cri-o, we'll need to check manually.

**Comment by LionelJouin** [comment]
If done in the same way as the the network namespace yes, it has to be done per runtime. 
With the way I sent, it uses only the CRI API, so I think it could be done in a common way.

**Comment by maiqueb** [comment]
> If done in the same way as the the network namespace yes, it has to be done per runtime. With the way I sent, it uses only the CRI API, so I think it could be done in a common way.

right; let's do it the proper way. 

Maybe we can even get rid of the runtime specific code to retrieve the network namespace using cri-api - I would assume that's also available there. This would be a follow-up. 

Tks for your research @LionelJouin
