### ISSUE TITLE
[RFE] Enable multi-platform support for  Multus Dynamic Networks Controller CNI image.

### ISSUE THREAD

**Issue by ashokpariya0** [k8snetworkplumbingwg/multus-dynamic-networks-controller#264]
**Is your feature request related to a problem? Please describe.**
The upstream image of the Multus Dynamic Networks Controller CNI (available at [this link](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pkgs/container/multus-dynamic-networks-controller)) currently supports only the `amd64` architecture. To extend its support, we should build a multi-platform image that includes support for the `s390x` and `arm64` architecture as well.

**Describe the solution you'd like**
Enable multi-platform support for building the image of Multus Dynamic Networks Controller CNI.

**Describe alternatives you've considered**

**Additional context**

**Comment by maiqueb** [comment]
I don't have time for this right now. 

If the community needs this fixed, the community can implement it.

And I have no clue how we'll test these builds work. This will be required as well. 

I'm not closing this issue, but I'll remove myself as an assignee.

**Comment by ashokpariya0** [comment]
@maiqueb With the proposed changes, I successfully built a multi-platform image supporting both amd64 and s390x architectures. I then deployed the Multus Dynamic Networks Controller CNI using the CNAO operator on a Kubernetes cluster running on s390x. I was able to run the E2E tests successfully on the s390x cluster.

Here are the results:
Ran 7 of 7 Specs in 93.268 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestDynamicNetworksControllerE2E (93.27s)
PASS
ok  	github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/e2e	93.281s

Is this sufficient to verify the correctness of the proposed changes? Also, I would appreciate it if you could provide more details regarding the image build process and the testing approach.

**Comment by maiqueb** [comment]
> @maiqueb With the proposed changes, I successfully built a multi-platform image supporting both amd64 and s390x architectures. I then deployed the Multus Dynamic Networks Controller CNI using the CNAO operator on a Kubernetes cluster running on s390x. I was able to run the E2E tests successfully on the s390x cluster.
> 
> Here are the results: Ran 7 of 7 Specs in 93.268 seconds SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped --- PASS: TestDynamicNetworksControllerE2E (93.27s) PASS ok github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/e2e 93.281s
> 
> Is this sufficient to verify the correctness of the proposed changes? Also, I would appreciate it if you could provide more details regarding the image build process and the testing approach.

This is good, but I wonder how can we assure this stays working ?... Can we have a lane on this architecture running on github's CI ? I really don't know. 

We could probably just plow through and accept the change - meaning, the only thing we test is that we can build imgs for  `s390x`. We wouldn't know if we can actually run them, or if their behavior is the expected.

**Comment by ashokpariya0** [comment]
@maiqueb I’ve implemented multi-platform build support in [PR #267](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/267) using GitHub Actions. Could you please review the changes?
