### ISSUE TITLE
[RFE] map the container image to the actual git commit

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-dynamic-networks-controller#73]
**Is your feature request related to a problem? Please describe.**
In order to proper debug user issues, we need an easy way to map the container image with the actual code running in it.

**Describe the solution you'd like**
Embed the git commit SHA into the image's metadata would be the cheapest way to achieve this.

**Describe alternatives you've considered**
Using LD flags and exposing a `--version` command would be an alternative, but it has the following drawbacks:
- requires code changes
- requires pulling the image
- requires running the image

**Comment by kmabda** [comment]
I think also logging the git release version, commit id and build time would also help debugging.

**Comment by maiqueb** [comment]
> 

Good point!

I agree this is useful, especially for production systems. 

Let's focus on this on a follow-up PR.

I'll open another issue.

For my understanding:
- we should log the commit ID from the running application (the controller)
- we should time the build time during `go build` - so this is just adding a line to the build script
- the git release version should also come from the CI system.

@kmabda

**Comment by kmabda** [comment]
@maiqueb agree.

Yes, for production system logging the git commit ID and the git release version are useful info for troubleshooting/filing an issue.
